import Testing
import Foundation
@testable import EditorKit
import EffectsKit

@Suite("AutoZoomDetector")
struct AutoZoomDetectorTests {

    // MARK: - Helpers

    /// Build a dwell run: N samples at the same (x, y) over [start, end].
    /// Timestamps are generated by index (`start + n * step`) rather than by
    /// accumulation, so they don't drift under IEEE 754 arithmetic.
    private func dwell(
        from start: TimeInterval,
        to end: TimeInterval,
        x: Double = 0.5,
        y: Double = 0.5,
        sampleRateHz: Double = 60
    ) -> [CursorEvent] {
        let step = 1.0 / sampleRateHz
        var out: [CursorEvent] = []
        var n = 0
        while true {
            let t = start + Double(n) * step
            if t > end { break }
            out.append(CursorEvent(timestamp: t, x: x, y: y, type: .move))
            n += 1
        }
        return out
    }

    private func click(
        at t: TimeInterval,
        x: Double = 0.5,
        y: Double = 0.5,
        type: CursorEventType = .leftClick
    ) -> CursorEvent {
        CursorEvent(timestamp: t, x: x, y: y, type: type)
    }

    // MARK: - Empty / trivial

    @Test("empty events returns empty result")
    func emptyEvents() {
        let out = AutoZoomDetector.detect(events: [], duration: 10)
        #expect(out.isEmpty)
    }

    // MARK: - Single click

    @Test("single click produces one segment with 1s pre-roll / 2s post-roll")
    func singleClick() {
        let out = AutoZoomDetector.detect(
            events: [click(at: 5.0, x: 0.3, y: 0.7)],
            duration: 10
        )
        #expect(out.count == 1)
        let seg = out[0]
        #expect(seg.startTime == 4.0)
        #expect(seg.endTime == 7.0)
        #expect(seg.zoomLevel == 1.5)
        #expect(seg.source == .auto)
        if case .manual(let x, let y) = seg.focusMode {
            #expect(x == 0.3)
            #expect(y == 0.7)
        } else {
            Issue.record("expected .manual focus mode, got \(seg.focusMode)")
        }
    }

    @Test("click near left boundary shifts segment right without shrinking")
    func clickClampedToLeftBoundary() {
        let out = AutoZoomDetector.detect(
            events: [click(at: 0.2)],
            duration: 10
        )
        #expect(out.count == 1)
        #expect(out[0].startTime == 0.0)
        #expect(out[0].endTime == 3.0)
    }

    @Test("click near right boundary shifts segment left without shrinking")
    func clickClampedToRightBoundary() {
        let out = AutoZoomDetector.detect(
            events: [click(at: 9.8)],
            duration: 10
        )
        #expect(out.count == 1)
        #expect(out[0].startTime == 7.0)
        #expect(out[0].endTime == 10.0)
    }

    // MARK: - Spacing

    @Test("two clicks within minSpacing — only earlier accepted")
    func twoClicksWithinSpacing() {
        // Both clicks have equal strength (1000). Tie break: earlier time wins.
        let out = AutoZoomDetector.detect(
            events: [click(at: 5.0), click(at: 5.5)],
            duration: 10
        )
        #expect(out.count == 1)
        #expect(out[0].startTime == 4.0)  // segment from click at 5.0
    }

    @Test("two clicks beyond minSpacing and not merged — both accepted")
    func twoClicksBeyondSpacing() {
        // Clicks at 3 and 8: center gap 5s ≥ minSpacing(1.8). Segments [2,5] and [7,10].
        // Segment gap 7-5=2 > mergeGap(1.5). Do not merge.
        let out = AutoZoomDetector.detect(
            events: [click(at: 3.0), click(at: 8.0)],
            duration: 12
        )
        #expect(out.count == 2)
        #expect(out[0].startTime == 2.0)
        #expect(out[1].startTime == 7.0)
    }

    // MARK: - Dwell

    @Test("dwell of 2s produces 3s segment centered on dwell midpoint")
    func dwellTwoSeconds() {
        // Dwell from t=4 to t=6 → midpoint=5, duration=max(3, 2+1)=3 → [3.5, 6.5]
        let out = AutoZoomDetector.detect(
            events: dwell(from: 4.0, to: 6.0, x: 0.25, y: 0.75),
            duration: 10
        )
        #expect(out.count == 1)
        #expect(out[0].startTime == 3.5)
        #expect(out[0].endTime == 6.5)
        if case .manual(let x, let y) = out[0].focusMode {
            #expect(abs(x - 0.25) < 0.001)
            #expect(abs(y - 0.75) < 0.001)
        } else {
            Issue.record("expected .manual focus mode")
        }
    }

    @Test("dwell shorter than minDwellDuration produces no segment")
    func dwellTooShort() {
        // 200ms of stillness — below the 450ms threshold.
        let out = AutoZoomDetector.detect(
            events: dwell(from: 4.0, to: 4.2),
            duration: 10
        )
        #expect(out.isEmpty)
    }

    @Test("dwell longer than maxDwellDuration produces no segment")
    func dwellTooLong() {
        // 3s of stillness — above the 2.6s threshold.
        let out = AutoZoomDetector.detect(
            events: dwell(from: 2.0, to: 5.0),
            duration: 10
        )
        #expect(out.isEmpty)
    }

    // MARK: - Mixed / merge

    @Test("click and distant dwell produce two separate segments")
    func clickAndDistantDwellBothAccepted() {
        // Click at t=3 → [2, 5]. Dwell [8.5, 10] → duration=1.5s, midpoint=9.25,
        // segment duration=max(3, 1.5+1)=3 → [7.75, 10.75].
        // centerTime gap |9.25 - 3| = 6.25 ≥ minSpacing(1.8). Both accepted.
        // Segment gap 7.75 - 5 = 2.75 > mergeGap(1.5). Do not merge.
        let events =
            dwell(from: 8.5, to: 10.0, x: 0.7, y: 0.7) +
            [click(at: 3.0, x: 0.2, y: 0.2)]
        let out = AutoZoomDetector.detect(events: events, duration: 12)
        #expect(out.count == 2)
        #expect(out[0].startTime == 2.0)
        #expect(out[0].endTime == 5.0)
        #expect(out[1].startTime == 7.75)
        #expect(out[1].endTime == 10.75)
    }

    @Test("overlapping segments after construction are merged")
    func overlappingSegmentsMerge() {
        // Click at t=3 → [2, 5]. Click at t=5.5 is within minSpacing of 3 (diff 2.5 > 1.8,
        // so both accepted). Segments [2, 5] and [4.5, 7.5] overlap → merged to [2, 7.5].
        let out = AutoZoomDetector.detect(
            events: [click(at: 3.0, x: 0.2, y: 0.2), click(at: 5.5, x: 0.8, y: 0.8)],
            duration: 12
        )
        #expect(out.count == 1)
        #expect(out[0].startTime == 2.0)
        #expect(out[0].endTime == 7.5)
        // Weighted focus: both segments have duration 3, so focus is the simple average.
        if case .manual(let x, let y) = out[0].focusMode {
            #expect(abs(x - 0.5) < 0.001)
            #expect(abs(y - 0.5) < 0.001)
        } else {
            Issue.record("expected .manual focus mode")
        }
    }

    @Test("two distant clicks do not merge")
    func distantClicksDontMerge() {
        let out = AutoZoomDetector.detect(
            events: [click(at: 2.0), click(at: 8.0)],
            duration: 12
        )
        #expect(out.count == 2)
    }

    // MARK: - Strength ranking

    @Test("long dwell outranks short dwell when within spacing")
    func strengthRankingDwell() {
        // Two non-overlapping dwells whose center times conflict:
        //   Short at t=[2.0, 2.5] → 500ms, strength=500, midpoint=2.25
        //   Long at t=[3.0, 5.0] → 2s, strength=2000, midpoint=4.0
        // centerTime gap |4.0 - 2.25| = 1.75 < minSpacing(1.8). Long wins.
        // Resulting segment (dwell dur=2s): duration=max(3, 2+1)=3, centered on 4.0 → [2.5, 5.5].
        let events =
            dwell(from: 2.0, to: 2.5, x: 0.1, y: 0.1) +
            dwell(from: 3.0, to: 5.0, x: 0.9, y: 0.9)
        let out = AutoZoomDetector.detect(events: events, duration: 10)
        #expect(out.count == 1)
        if case .manual(let x, _) = out[0].focusMode {
            // Short dwell x=0.1; long dwell x=0.9. Long wins → x should be ~0.9.
            #expect(x > 0.5)
        } else {
            Issue.record("expected .manual focus mode")
        }
    }
}
